dist: trusty
language: java
jdk:
  - oraclejdk8
branches:
  except:
  - logo_submission

script: "mvn clean test -Djacoco.skip=false"

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
